name: Trigger Mirror

on: push

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MIRROR_TOKEN }}" \
            "https://api.github.com/repos/CliCli-Editor/workflow/dispatches" \
            -d '{"event_type": "trigger_mirror"}'
